package com.nyuen.dxtest.dao;

import com.nyuen.dxtest.model.DbsnpGrch37;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface DbsnpGrch37Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37
     *
     * @mbg.generated Fri Sep 13 11:17:35 CST 2019
     */
    int deleteByPrimaryKey(@Param("chr") String chr, @Param("pos") Integer pos, @Param("ref") String ref, @Param("alt") String alt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37
     *
     * @mbg.generated Fri Sep 13 11:17:35 CST 2019
     */
    int insert(DbsnpGrch37 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37
     *
     * @mbg.generated Fri Sep 13 11:17:35 CST 2019
     */
    int insertSelective(DbsnpGrch37 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37
     *
     * @mbg.generated Fri Sep 13 11:17:35 CST 2019
     */
    DbsnpGrch37 selectByPrimaryKey(@Param("chr") String chr, @Param("pos") Integer pos, @Param("ref") String ref, @Param("alt") String alt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37
     *
     * @mbg.generated Fri Sep 13 11:17:35 CST 2019
     */
    int updateByPrimaryKeySelective(DbsnpGrch37 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37
     *
     * @mbg.generated Fri Sep 13 11:17:35 CST 2019
     */
    int updateByPrimaryKey(DbsnpGrch37 record);

    //返回所有数据
    List<DbsnpGrch37> getAllData();

    //返回总条数
    int getTotalCount();

    //条件查询
    List<DbsnpGrch37> selectByCondition(Map<String,Object> params);
    //条件查询返回总条数
    int getTotalCountByCondition(Map<String, Object> params);
}
