package com.nyuen.dxtest.dao;

import com.nyuen.dxtest.model.DbsnpGrch37Log;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface DbsnpGrch37LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37_log
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37_log
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    int insert(DbsnpGrch37Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37_log
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    int insertSelective(DbsnpGrch37Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37_log
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    DbsnpGrch37Log selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37_log
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    int updateByPrimaryKeySelective(DbsnpGrch37Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbsnp_grch37_log
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    int updateByPrimaryKey(DbsnpGrch37Log record);

    List<DbsnpGrch37Log> getLog(Map<String, Object> params);
}
