package com.nyuen.dxtest.model;

public class DbsnpGrch37 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37.chr
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    private String chr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37.pos
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    private Integer pos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37.ref
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    private String ref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37.alt
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    private String alt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37.rs_id
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    private String rsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37.common_state
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    private Integer commonState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37.is_delete
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37.chr
     *
     * @return the value of dbsnp_grch37.chr
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public String getChr() {
        return chr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37.chr
     *
     * @param chr the value for dbsnp_grch37.chr
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public void setChr(String chr) {
        this.chr = chr == null ? null : chr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37.pos
     *
     * @return the value of dbsnp_grch37.pos
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37.pos
     *
     * @param pos the value for dbsnp_grch37.pos
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public void setPos(Integer pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37.ref
     *
     * @return the value of dbsnp_grch37.ref
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37.ref
     *
     * @param ref the value for dbsnp_grch37.ref
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public void setRef(String ref) {
        this.ref = ref == null ? null : ref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37.alt
     *
     * @return the value of dbsnp_grch37.alt
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public String getAlt() {
        return alt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37.alt
     *
     * @param alt the value for dbsnp_grch37.alt
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public void setAlt(String alt) {
        this.alt = alt == null ? null : alt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37.rs_id
     *
     * @return the value of dbsnp_grch37.rs_id
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public String getRsId() {
        return rsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37.rs_id
     *
     * @param rsId the value for dbsnp_grch37.rs_id
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public void setRsId(String rsId) {
        this.rsId = rsId == null ? null : rsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37.common_state
     *
     * @return the value of dbsnp_grch37.common_state
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public Integer getCommonState() {
        return commonState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37.common_state
     *
     * @param commonState the value for dbsnp_grch37.common_state
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public void setCommonState(Integer commonState) {
        this.commonState = commonState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37.is_delete
     *
     * @return the value of dbsnp_grch37.is_delete
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37.is_delete
     *
     * @param isDelete the value for dbsnp_grch37.is_delete
     *
     * @mbg.generated Wed Oct 09 15:38:19 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}
