package com.nyuen.dxtest.model;

import java.util.Date;

public class DbsnpGrch37Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.id
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.operate_table_name
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private String operateTableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.operate_column_name
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private String operateColumnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.old_data
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private String oldData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.new_data
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private String newData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.operate_user
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private String operateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.operate_time
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.chr
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private String chr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.pos
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private Integer pos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.ref
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private String ref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbsnp_grch37_log.alt
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    private String alt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.id
     *
     * @return the value of dbsnp_grch37_log.id
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.id
     *
     * @param id the value for dbsnp_grch37_log.id
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.operate_table_name
     *
     * @return the value of dbsnp_grch37_log.operate_table_name
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public String getOperateTableName() {
        return operateTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.operate_table_name
     *
     * @param operateTableName the value for dbsnp_grch37_log.operate_table_name
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setOperateTableName(String operateTableName) {
        this.operateTableName = operateTableName == null ? null : operateTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.operate_column_name
     *
     * @return the value of dbsnp_grch37_log.operate_column_name
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public String getOperateColumnName() {
        return operateColumnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.operate_column_name
     *
     * @param operateColumnName the value for dbsnp_grch37_log.operate_column_name
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setOperateColumnName(String operateColumnName) {
        this.operateColumnName = operateColumnName == null ? null : operateColumnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.old_data
     *
     * @return the value of dbsnp_grch37_log.old_data
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public String getOldData() {
        return oldData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.old_data
     *
     * @param oldData the value for dbsnp_grch37_log.old_data
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setOldData(String oldData) {
        this.oldData = oldData == null ? null : oldData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.new_data
     *
     * @return the value of dbsnp_grch37_log.new_data
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public String getNewData() {
        return newData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.new_data
     *
     * @param newData the value for dbsnp_grch37_log.new_data
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setNewData(String newData) {
        this.newData = newData == null ? null : newData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.operate_user
     *
     * @return the value of dbsnp_grch37_log.operate_user
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public String getOperateUser() {
        return operateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.operate_user
     *
     * @param operateUser the value for dbsnp_grch37_log.operate_user
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setOperateUser(String operateUser) {
        this.operateUser = operateUser == null ? null : operateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.operate_time
     *
     * @return the value of dbsnp_grch37_log.operate_time
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.operate_time
     *
     * @param operateTime the value for dbsnp_grch37_log.operate_time
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.chr
     *
     * @return the value of dbsnp_grch37_log.chr
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public String getChr() {
        return chr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.chr
     *
     * @param chr the value for dbsnp_grch37_log.chr
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setChr(String chr) {
        this.chr = chr == null ? null : chr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.pos
     *
     * @return the value of dbsnp_grch37_log.pos
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.pos
     *
     * @param pos the value for dbsnp_grch37_log.pos
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setPos(Integer pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.ref
     *
     * @return the value of dbsnp_grch37_log.ref
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.ref
     *
     * @param ref the value for dbsnp_grch37_log.ref
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setRef(String ref) {
        this.ref = ref == null ? null : ref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbsnp_grch37_log.alt
     *
     * @return the value of dbsnp_grch37_log.alt
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public String getAlt() {
        return alt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbsnp_grch37_log.alt
     *
     * @param alt the value for dbsnp_grch37_log.alt
     *
     * @mbg.generated Thu Sep 26 16:27:19 CST 2019
     */
    public void setAlt(String alt) {
        this.alt = alt == null ? null : alt.trim();
    }
}
